# Generated by Django 6.0.1 on 2026-01-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
