# Generated by Django 6.0.1 on 2026-01-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_emailverificationtoken_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verified',
        ),
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
