# Generated by Django 6.0.1 on 2026-01-27 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_remove_userprofile_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
