name: Build and deploy Python app to Azure Web App - inkspire

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install --upgrade pip
          if [ -f complete-blogging-system/requirements.txt ]; then pip install -r complete-blogging-system/requirements.txt; fi

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            complete-blogging-system/
            !complete-blogging-system/antenv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_9987C70146B642E5923F4F86A78CB691 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D93861D381FE4B218F35BEFF3E71D47F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0BB7823EDE0947CFB520B190046DB9C8 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'inkspire'
          slot-name: 'Production'
          package: '.'